FROM nginx:latest

COPY nginx.production.conf /etc/nginx/nginx.conf
COPY frontend-server.production.conf /etc/nginx/sites-available/frontend-server.conf

COPY ./dist/frontend /var/www/frontend

RUN mkdir /etc/nginx/sites-enabled
RUN ln -s /etc/nginx/sites-available/ /etc/nginx/sites-enabled/

EXPOSE 4200
