# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: local 
    hooks:
    -   id: pylint
        name: pylint
        entry: bash -c 'cd backend && pip install -r requirements.txt && prospector -X'
        language: python
