version: "3"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.production
    ports:
      - "8000:8000"
    user: "${UID}:${GID}"
    networks:
      ledger-board-network:
        ipv4_address: ${LEDGER_BOARD_BACKEND}

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.production
    ports:
      - "4200:4200"
    networks:
      ledger-board-network:
        ipv4_address: ${LEDGER_BOARD_FRONTEND}
    environment:
      - BACKEND_IP=${LEDGER_BOARD_BACKEND}

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    network_mode: "host"
    tty: true

networks:
 ledger-board-network:
   ipam:
     driver: default
     config:
       - subnet: ${SUBNET_IP}
