version: "3"

services:
  backend:
    build: ./backend
    user: "${UID}:${GID}"
    networks:
      ledger-board-network:
        ipv4_address: ${LEDGER_BOARD_BACKEND}
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/home/docker/app
    tty: true

  frontend:
    build: ./frontend
    user: "${UID}:${GID}"
    networks:
      ledger-board-network:
        ipv4_address: ${LEDGER_BOARD_FRONTEND}
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/home/docker/app
    environment:
      - BACKEND_IP=${LEDGER_BOARD_BACKEND}

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    network_mode: "host"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    tty: true

networks:
 ledger-board-network:
   ipam:
     driver: default
     config:
       - subnet: ${SUBNET_IP}
