output-format: emacs
strictness: veryhigh
doc-warnings: yes
ignore-paths:
  - backend/
  - manage.py
  - gunicorn.conf.py
  - receiver/migrations
  - receiver/admin.py
  - receiver/apps.py
  - receiver/__init__.py
  - sender/migrations
  - sender/admin.py
  - sender/apps.py
  - sender/__init__.py
  - polls/migrations
  - polls/admin.py
  - polls/apps.py
  - polls/__init__.py

pydocstyle:
  disable:
    - D211
