output-format: emacs
strictness: medium
doc-warnings: yes
ignore-paths:
  - backend/
  - manage.py
  - gunicorn.conf.py
  - receiver/migrations
  - receiver/admin.py
  - receiver/apps.py
  - receiver/__init__.py
  - sender/migrations
  - sender/admin.py
  - sender/apps.py
  - sender/__init__.py
  - sender/views/__init__.py
  - sender/utils/__init__py
  - sender/tests/__init__.py

pydocstyle:
  disable:
    - D211
    - D205
    - D213
    - D212
    - D208
