apiVersion: v1
kind: Service
metadata:
  name: ledger-board-nginx-service
spec:
  selector:
    app: ledger-board-application
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
